(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: ProjetoA110
 * File: ProjetoA110Init.st
 * Author: supervisorio
 * Created: November 18, 2023
 ********************************************************************
 * Implementation of program ProjetoA110
 ********************************************************************)

PROGRAM _INIT

	SETPOINT := 50.0;
	MAX_TEMP_PERMITIDA := 75.0;
	
END_PROGRAM

